services:
  database:
    image: postgres:latest
    container_name: "test_prisma_posgresql"
    restart: always
    environment:
      - POSTGRES_USER=eliphaz
      - POSTGRES_PASSWORD=supersecr3t
      - POSTGRES_DB=testprismadb
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
      - '5439:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8069:8080'

volumes:
  postgres:

